import { Header } from '@/views/components/Header'
import { ReactNode } from 'react'
import './globals.css'
import { Montserrat } from 'next/font/google'

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

const montserrat = Montserrat({
   subsets: ['latin'],
   display: 'swap',
})

export default function RootLayout({ children }: { children: ReactNode }) {
   return (
      <html lang="pt-br" className={montserrat.className}>
         <body>
            <Header />
            {children}
         </body>
      </html>
   )
}
